// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IStaking$Type } from "./IStaking";
import { ProposalStructs$Type } from "./ProposalStructs";
import { StakingStructs$Type } from "./StakingStructs";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IStaking"]: IStaking$Type;
    ["ProposalStructs"]: ProposalStructs$Type;
    ["StakingStructs"]: StakingStructs$Type;
    ["@evvm/testnet-contracts/interfaces/IStaking.sol:IStaking"]: IStaking$Type;
    ["@evvm/testnet-contracts/interfaces/IStaking.sol:ProposalStructs"]: ProposalStructs$Type;
    ["@evvm/testnet-contracts/interfaces/IStaking.sol:StakingStructs"]: StakingStructs$Type;
  }
}
