// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ProposalStructs$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ProposalStructs",
  "sourceName": "@evvm/testnet-contracts/interfaces/IStaking.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122038fd5dfd443b91b549997d229266d6cc769807a43782d5a25761048edd3056f464736f6c634300081c0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122038fd5dfd443b91b549997d229266d6cc769807a43782d5a25761048edd3056f464736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "@evvm/testnet-contracts/interfaces/IStaking.sol:ProposalStructs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ProposalStructs$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "@evvm/testnet-contracts/interfaces/IStaking.sol:ProposalStructs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ProposalStructs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "@evvm/testnet-contracts/interfaces/IStaking.sol:ProposalStructs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ProposalStructs$Type["abi"]>>;
}
