// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface StakingStructs$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "StakingStructs",
  "sourceName": "@evvm/testnet-contracts/interfaces/IStaking.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212200c111dc1de485d7a8420c909802485f50a51a1be19e3a0f8e7ed6b0bc3ffabd564736f6c634300081c0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212200c111dc1de485d7a8420c909802485f50a51a1be19e3a0f8e7ed6b0bc3ffabd564736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "StakingStructs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<StakingStructs$Type["abi"]>>;
  export function deployContract(
    contractName: "@evvm/testnet-contracts/interfaces/IStaking.sol:StakingStructs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<StakingStructs$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "StakingStructs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<StakingStructs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@evvm/testnet-contracts/interfaces/IStaking.sol:StakingStructs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<StakingStructs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "StakingStructs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<StakingStructs$Type["abi"]>>;
  export function getContractAt(
    contractName: "@evvm/testnet-contracts/interfaces/IStaking.sol:StakingStructs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<StakingStructs$Type["abi"]>>;
}
