// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CoreStructs$Type } from "./CoreStructs";
import { ICore$Type } from "./ICore";
import { ProposalStructs$Type } from "./ProposalStructs";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CoreStructs"]: CoreStructs$Type;
    ["ICore"]: ICore$Type;
    ["ProposalStructs"]: ProposalStructs$Type;
    ["@evvm/testnet-contracts/interfaces/ICore.sol:CoreStructs"]: CoreStructs$Type;
    ["@evvm/testnet-contracts/interfaces/ICore.sol:ICore"]: ICore$Type;
    ["@evvm/testnet-contracts/interfaces/ICore.sol:ProposalStructs"]: ProposalStructs$Type;
  }
}
