// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface CoreStructs$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "CoreStructs",
  "sourceName": "@evvm/testnet-contracts/interfaces/ICore.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f019e1fd365bc09b284f0d32d6714a017e1cfc1d99f9fa6c25bcacf1445871d664736f6c634300081c0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f019e1fd365bc09b284f0d32d6714a017e1cfc1d99f9fa6c25bcacf1445871d664736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "CoreStructs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreStructs$Type["abi"]>>;
  export function deployContract(
    contractName: "@evvm/testnet-contracts/interfaces/ICore.sol:CoreStructs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreStructs$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "CoreStructs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreStructs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@evvm/testnet-contracts/interfaces/ICore.sol:CoreStructs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreStructs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "CoreStructs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreStructs$Type["abi"]>>;
  export function getContractAt(
    contractName: "@evvm/testnet-contracts/interfaces/ICore.sol:CoreStructs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreStructs$Type["abi"]>>;
}
